### ISSUE TITLE
Enqueue plugin stylesheets outside of UCF_Events_Common::display_events()

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Events-Plugin#1]
https://github.com/UCF/UCF-Events-Plugin/blob/master/includes/ucf-events-common.php#L10-L14

Plugin styles need to be enqueued outside of this function (and always be enqueued, regardless of whether or not events are displayed on the page), due to wp_enqueue_styles() being called too late during execution.  It being called so late will result in inconsistent enqueuing results over https vs http due to timing differences.

**Comment by jmbarne3** [comment]
Solved in #3 and released in [v1.0.1](https://github.com/UCF/UCF-Events-Plugin/tree/v1.0.1).
