### ISSUE TITLE
keep getting call to undefined error, have to manually remove plugin

### ISSUE THREAD

**Issue by shelaine** [UCF/UCF-Events-Plugin#24]
Fatal error: Call to undefined function is_plugin_active() in /srv/bindings/7edd3bfd73184ee58978dd4c167533d0/code/wp-content/plugins/UCF-Events-Plugin-master/ucf-events.php on line 50 

Keep getting the above error. I installed via upload in the wordpress dashboard. Any idea why this keeps happening?

I would like to use the plugin for the new UCF Sustainability site. Thanks!

**Comment by cjg89** [comment]
Hi @shelaine, we just published a new version of the plugin that removes the offending function and should fix this problem.  Please remove the old version and install the latest version (https://github.com/UCF/UCF-Events-Plugin/releases/tag/v2.1.1) and let us know if you're still having any issues activating it.  Thanks!

**Comment by shelaine** [comment]
Thanks so much, the error is fixed

However besides going to settings > ucf events to edit basic settings, I do not see a shortcode option or any explanation for adding the calendar to a page.

**Comment by cjg89** [comment]
@shelaine We have a wiki set up with usage instructions here:  https://github.com/UCF/UCF-Events-Plugin/wiki

I'm going to close this issue since the bug is fixed; if you encounter any other issues using the plugin, please open a new issue.  Thank you!
