### ISSUE TITLE
Add note next to transient expiration field about '0' values

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Events-Plugin#28]
Add a note that explains that a '0' expiration value will cause the feed to never expire.

Alternatively we may want to consider preventing the user from providing a '0' value at all.

**Comment by vinhtvu2** [comment]
I totally agree :-) Just had a ticket with this issue because transient expiration wasn't set. Installed transient manager and the events transient show "Does not expire".
We should set a default to 24 hours or something like that.

**Comment by cjg89** [comment]
Resolved in v2.1.3.
